# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-48c52457-cfe2-40b8-868a-bbf656e21a57";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-48c52457-cfe2-40b8-868a-bbf656e21a57".device = "/dev/disk/by-uuid/48c52457-cfe2-40b8-868a-bbf656e21a57";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6B04-4E38";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-950ab67a-8dae-4740-8838-3fd82f7bab20"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
